import type { ScenarioDefinition } from "../../types";

const SHOW_WHEN_ERROR = { path: "state.ui.error", exists: true } as const;
const SHOW_WHEN_READY = { not: SHOW_WHEN_ERROR } as const;

export const gtmOpsScenario: ScenarioDefinition = {
  id: "ops-gtm-dashboard",
  type: "tool",
  version: 3,
  title: "GTM Engine Dashboard",
  description: "Channel-level acquisition performance, spend efficiency, and scaling signals.",
  layout: {
    panels: [
      {
        id: "gtm-hero",
        kind: "hero",
        renderer: "dom",
        kicker: "GTM Engine",
        title: "GTM Engine Dashboard",
        subtitle: "Channel-level acquisition performance, spend efficiency, and scaling signals.",
        meta: "Window: {{state.global.dashboard.headline.window_days}}d · Updated: {{state.global.dashboard.headline.computed_at}}",
      },
      {
        id: "gtm-actions",
        kind: "section",
        renderer: "dom",
        children: [
          {
            id: "gtm-action-row",
            kind: "actions",
            renderer: "dom",
            actions: [
              { id: "gtm-refresh", label: "Refresh dashboard", tone: "primary", interactionId: "gtm.refresh" },
            ],
          },
          {
            id: "gtm-status-message",
            kind: "text",
            renderer: "dom",
            text: "{{state.ui.status_message}}",
            tone: "success",
          },
        ],
      },
      {
        id: "gtm-error-section",
        kind: "section",
        renderer: "dom",
        title: "GTM dashboard is unavailable",
        subtitle: "Ingest spend and campaign data, then refresh this mini-app.",
        visibleWhen: SHOW_WHEN_ERROR,
        children: [
          {
            id: "gtm-error-message",
            kind: "text",
            renderer: "dom",
            text: "{{state.ui.error}}",
            tone: "danger",
          },
        ],
      },
      {
        id: "gtm-metrics-section",
        kind: "section",
        renderer: "dom",
        title: "Headline metrics",
        subtitle: "Acquisition and monetization pulse for GTM channels.",
        visibleWhen: SHOW_WHEN_READY,
        children: [
          {
            id: "gtm-metrics-grid",
            kind: "metric_grid",
            renderer: "dom",
            columns: 8,
            items: [
              { id: "gtm-traffic", label: "Traffic", value: { from: "state.global.dashboard.headline.traffic_sessions" }, format: "number" },
              { id: "gtm-signups", label: "Signups", value: { from: "state.global.dashboard.headline.signups" }, format: "number" },
              { id: "gtm-activated", label: "Activated", value: { from: "state.global.dashboard.headline.activated_users" }, format: "number" },
              { id: "gtm-paid", label: "Paid", value: { from: "state.global.dashboard.headline.paid_users" }, format: "number" },
              { id: "gtm-revenue", label: "Revenue", value: { from: "state.global.dashboard.headline.revenue_usd" }, format: "usd" },
              { id: "gtm-spend", label: "Spend", value: { from: "state.global.dashboard.headline.spend_usd" }, format: "usd" },
              { id: "gtm-cac", label: "Blended CAC", value: { from: "state.global.dashboard.headline.blended_cac_usd" }, format: "usd" },
              {
                id: "gtm-roi",
                label: "Blended ROI",
                value: { from: "state.global.dashboard.headline.blended_roi_percent" },
                format: "percent",
              },
            ],
          },
        ],
      },
      {
        id: "gtm-form-section",
        kind: "section",
        renderer: "dom",
        title: "Cost ingestion",
        subtitle: "Add or update channel spend directly from the generated runtime form.",
        visibleWhen: SHOW_WHEN_READY,
        children: [
          {
            id: "gtm-spend-form-node",
            kind: "form",
            renderer: "dom",
            formId: "gtm_spend",
            fieldIds: [
              "gtm-spend-day",
              "gtm-source",
              "gtm-medium",
              "gtm-campaign",
              "gtm-cost",
              "gtm-clicks",
              "gtm-impressions",
              "gtm-ad-id",
              "gtm-creative-id",
              "gtm-dedupe-key",
            ],
            submitLabel: "Save spend entry",
            submitInteractionId: "gtm.submit.spend",
          },
          {
            id: "gtm-submit-message",
            kind: "text",
            renderer: "dom",
            text: "{{state.ui.submit_message}}",
            tone: "success",
          },
        ],
      },
      {
        id: "gtm-channel-section",
        kind: "section",
        renderer: "dom",
        title: "Channel performance",
        subtitle: "Acquisition, activation, spend and monetization by source/campaign.",
        visibleWhen: SHOW_WHEN_READY,
        children: [
          {
            id: "gtm-channel-table",
            kind: "table",
            renderer: "dom",
            source: "global.dashboard.channels",
            emptyText: "No channel rows in this window.",
            columns: [
              { key: "source", label: "Source", format: "text" },
              { key: "campaign", label: "Campaign", format: "text" },
              { key: "traffic_sessions", label: "Traffic", format: "number" },
              { key: "signups", label: "Signups", format: "number" },
              { key: "paid_users", label: "Paid", format: "number" },
              { key: "revenue_usd", label: "Revenue", format: "usd" },
              { key: "cac_usd", label: "CAC", format: "usd" },
              { key: "roi_percent", label: "ROI", format: "percent" },
            ],
          },
        ],
      },
      {
        id: "gtm-funnel-section",
        kind: "section",
        renderer: "dom",
        title: "Funnel by source",
        subtitle: "How each source moves from acquisition to paid conversion.",
        visibleWhen: SHOW_WHEN_READY,
        children: [
          {
            id: "gtm-funnel-table",
            kind: "table",
            renderer: "dom",
            source: "global.dashboard.funnel_by_source",
            emptyText: "No source funnel rows available.",
            columns: [
              { key: "source", label: "Source", format: "text" },
              { key: "acquired", label: "Acquired", format: "number" },
              { key: "signed_up", label: "Signed up", format: "number" },
              { key: "activated", label: "Activated", format: "number" },
              { key: "paid", label: "Paid", format: "number" },
              { key: "acquired_to_signup", label: "Acq→Signup", format: "percent" },
              { key: "signup_to_activated", label: "Signup→Activated", format: "percent" },
              { key: "activated_to_paid", label: "Activated→Paid", format: "percent" },
            ],
          },
        ],
      },
      {
        id: "gtm-top-campaigns-section",
        kind: "section",
        renderer: "dom",
        title: "Top campaigns",
        subtitle: "Campaigns ranked by revenue and efficiency.",
        visibleWhen: SHOW_WHEN_READY,
        children: [
          {
            id: "gtm-top-campaigns-table",
            kind: "table",
            renderer: "dom",
            source: "global.dashboard.top_campaigns",
            emptyText: "No campaign rows captured.",
            columns: [
              { key: "source", label: "Source", format: "text" },
              { key: "campaign", label: "Campaign", format: "text" },
              { key: "revenue_usd", label: "Revenue", format: "usd" },
              { key: "roi_percent", label: "ROI", format: "percent" },
              { key: "conversion_rate", label: "Conversion", format: "percent" },
            ],
          },
        ],
      },
      {
        id: "gtm-top-creatives-section",
        kind: "section",
        renderer: "dom",
        gateId: "creative_depth",
        title: "Top creatives",
        subtitle: "Ad-level and creative-level monetization signals.",
        visibleWhen: SHOW_WHEN_READY,
        children: [
          {
            id: "gtm-top-creatives-table",
            kind: "table",
            renderer: "dom",
            source: "global.dashboard.top_creatives",
            emptyText: "No creative rows available yet.",
            columns: [
              { key: "source", label: "Source", format: "text" },
              { key: "campaign", label: "Campaign", format: "text" },
              { key: "ad_id", label: "Ad ID", format: "text" },
              { key: "creative_id", label: "Creative ID", format: "text" },
              { key: "revenue_usd", label: "Revenue", format: "usd" },
              { key: "conversion_rate", label: "Conversion", format: "percent" },
            ],
          },
        ],
      },
      {
        id: "gtm-signals-section",
        kind: "section",
        renderer: "dom",
        title: "Scaling signals",
        subtitle: "Auto-generated scale/kill decisions from spend, ROI, and conversion quality.",
        visibleWhen: SHOW_WHEN_READY,
        children: [
          {
            id: "gtm-signals-cards",
            kind: "card_list",
            renderer: "dom",
            source: "global.dashboard.signals",
            emptyText: "No scale/kill signals in current window.",
            titleField: "signal",
            subtitleField: "reason",
            fields: [
              { key: "source", label: "Source", format: "text" },
              { key: "campaign", label: "Campaign", format: "text" },
              { key: "roi_percent", label: "ROI", format: "percent" },
              { key: "cac_usd", label: "CAC", format: "usd" },
              { key: "conversion_rate", label: "Conv", format: "percent" },
            ],
            columns: 2,
          },
          {
            id: "gtm-signals-canvas",
            kind: "canvas",
            renderer: "canvas",
            source: "global.dashboard.signals",
            chart: "dots",
            height: 180,
          },
        ],
      },
      {
        id: "gtm-stream-section",
        kind: "section",
        renderer: "dom",
        title: "Runtime stream",
        subtitle: "Execution logs for refreshes and spend submissions.",
        children: [
          {
            id: "gtm-stream",
            kind: "stream",
            renderer: "stream",
            source: "streams.activity",
            maxLines: 10,
            emptyText: "No runtime events yet.",
          },
        ],
      },
    ],
  },
  inputs: {
    fields: [
      {
        id: "gtm-spend-day",
        formId: "gtm_spend",
        label: "Spend day",
        type: "date",
        bind: "local.forms.gtm_spend.spend_day",
        required: true,
        interactionId: "gtm.input.spend_day",
      },
      {
        id: "gtm-source",
        formId: "gtm_spend",
        label: "Source",
        type: "text",
        bind: "local.forms.gtm_spend.source",
        placeholder: "google",
        required: true,
        interactionId: "gtm.input.source",
      },
      {
        id: "gtm-medium",
        formId: "gtm_spend",
        label: "Medium",
        type: "text",
        bind: "local.forms.gtm_spend.medium",
        placeholder: "ads",
        interactionId: "gtm.input.medium",
      },
      {
        id: "gtm-campaign",
        formId: "gtm_spend",
        label: "Campaign",
        type: "text",
        bind: "local.forms.gtm_spend.campaign",
        placeholder: "q2_launch",
        interactionId: "gtm.input.campaign",
      },
      {
        id: "gtm-cost",
        formId: "gtm_spend",
        label: "Cost (USD)",
        type: "number",
        bind: "local.forms.gtm_spend.cost_usd",
        min: 0,
        step: 0.01,
        inputMode: "decimal",
        required: true,
        placeholder: "120.00",
        interactionId: "gtm.input.cost_usd",
      },
      {
        id: "gtm-clicks",
        formId: "gtm_spend",
        label: "Clicks",
        type: "number",
        bind: "local.forms.gtm_spend.clicks",
        min: 0,
        step: 1,
        inputMode: "numeric",
        placeholder: "0",
        interactionId: "gtm.input.clicks",
      },
      {
        id: "gtm-impressions",
        formId: "gtm_spend",
        label: "Impressions",
        type: "number",
        bind: "local.forms.gtm_spend.impressions",
        min: 0,
        step: 1,
        inputMode: "numeric",
        placeholder: "0",
        interactionId: "gtm.input.impressions",
      },
      {
        id: "gtm-ad-id",
        formId: "gtm_spend",
        label: "Ad ID",
        type: "text",
        bind: "local.forms.gtm_spend.ad_id",
        placeholder: "ad_44",
        interactionId: "gtm.input.ad_id",
      },
      {
        id: "gtm-creative-id",
        formId: "gtm_spend",
        label: "Creative ID",
        type: "text",
        bind: "local.forms.gtm_spend.creative_id",
        placeholder: "creative_2",
        interactionId: "gtm.input.creative_id",
      },
      {
        id: "gtm-dedupe-key",
        formId: "gtm_spend",
        label: "Dedupe key (optional)",
        type: "text",
        bind: "local.forms.gtm_spend.dedupe_key",
        placeholder: "google-q2-launch-2026-04-06",
        interactionId: "gtm.input.dedupe_key",
      },
    ],
    interactions: [
      { id: "gtm.refresh", type: "click", source: "gtm.refresh", emits: "app/refresh" },
      {
        id: "gtm.submit.spend",
        type: "submit",
        source: "gtm_spend",
        emits: "gtm/spend-submit",
      },
      {
        id: "gtm.input.spend_day",
        type: "input",
        source: "gtm-spend-day",
        emits: "form/update",
        payload: {
          bind: { from: "interaction.bind" },
          value: { from: "interaction.value" },
        },
      },
      {
        id: "gtm.input.source",
        type: "input",
        source: "gtm-source",
        emits: "form/update",
        payload: {
          bind: { from: "interaction.bind" },
          value: { from: "interaction.value" },
        },
      },
      {
        id: "gtm.input.medium",
        type: "input",
        source: "gtm-medium",
        emits: "form/update",
        payload: {
          bind: { from: "interaction.bind" },
          value: { from: "interaction.value" },
        },
      },
      {
        id: "gtm.input.campaign",
        type: "input",
        source: "gtm-campaign",
        emits: "form/update",
        payload: {
          bind: { from: "interaction.bind" },
          value: { from: "interaction.value" },
        },
      },
      {
        id: "gtm.input.cost_usd",
        type: "input",
        source: "gtm-cost",
        emits: "form/update",
        payload: {
          bind: { from: "interaction.bind" },
          value: { from: "interaction.value" },
        },
      },
      {
        id: "gtm.input.clicks",
        type: "input",
        source: "gtm-clicks",
        emits: "form/update",
        payload: {
          bind: { from: "interaction.bind" },
          value: { from: "interaction.value" },
        },
      },
      {
        id: "gtm.input.impressions",
        type: "input",
        source: "gtm-impressions",
        emits: "form/update",
        payload: {
          bind: { from: "interaction.bind" },
          value: { from: "interaction.value" },
        },
      },
      {
        id: "gtm.input.ad_id",
        type: "input",
        source: "gtm-ad-id",
        emits: "form/update",
        payload: {
          bind: { from: "interaction.bind" },
          value: { from: "interaction.value" },
        },
      },
      {
        id: "gtm.input.creative_id",
        type: "input",
        source: "gtm-creative-id",
        emits: "form/update",
        payload: {
          bind: { from: "interaction.bind" },
          value: { from: "interaction.value" },
        },
      },
      {
        id: "gtm.input.dedupe_key",
        type: "input",
        source: "gtm-dedupe-key",
        emits: "form/update",
        payload: {
          bind: { from: "interaction.bind" },
          value: { from: "interaction.value" },
        },
      },
    ],
  },
  logic: {
    entryEvents: ["app/init"],
    steps: [
      {
        id: "gtm-init-default-date",
        on: "app/init",
        actions: [
          {
            kind: "invoke",
            actionId: "runtime.nowDate",
            assign: "local.forms.gtm_spend.spend_day",
          },
        ],
      },
      {
        id: "gtm-init-load-dashboard",
        on: "app/init",
        actions: [
          { kind: "set", target: "ui.loading", value: true },
          { kind: "clear", target: "ui.error" },
          {
            kind: "invoke",
            actionId: "analytics.fetchGtmDashboard",
            input: {
              window_days: { from: "state.local.filters.window_days", fallback: 30 },
            },
            assign: "global.dashboard",
            onErrorAssign: "ui.error",
          },
          {
            kind: "append",
            target: "streams.activity",
            value: { template: "{{event.at}} · gtm dashboard loaded" },
          },
          { kind: "set", target: "ui.status_message", value: "GTM runtime synced." },
          { kind: "set", target: "ui.loading", value: false },
          { kind: "persist", scope: "local" },
        ],
      },
      {
        id: "gtm-form-update",
        on: "form/update",
        actions: [{ kind: "set_path", targetFrom: "bind", valueFrom: "value" }],
      },
      {
        id: "gtm-submit",
        on: "gtm/spend-submit",
        actions: [
          {
            kind: "check_limit",
            limitId: "gtm_submit",
            ifExceededEvent: "gtm/submit-limit-exceeded",
          },
          { kind: "clear", target: "ui.error" },
          {
            kind: "invoke",
            actionId: "analytics.upsertGtmSpend",
            input: {
              spend_day: { from: "state.local.forms.gtm_spend.spend_day" },
              source: { from: "state.local.forms.gtm_spend.source" },
              medium: { from: "state.local.forms.gtm_spend.medium" },
              campaign: { from: "state.local.forms.gtm_spend.campaign" },
              ad_id: { from: "state.local.forms.gtm_spend.ad_id" },
              creative_id: { from: "state.local.forms.gtm_spend.creative_id" },
              cost_usd: { from: "state.local.forms.gtm_spend.cost_usd" },
              clicks: { from: "state.local.forms.gtm_spend.clicks" },
              impressions: { from: "state.local.forms.gtm_spend.impressions" },
              dedupe_key: { from: "state.local.forms.gtm_spend.dedupe_key" },
            },
            assign: "local.gtm.last_submit",
            onErrorAssign: "ui.error",
          },
          { kind: "set", target: "ui.submit_message", value: { from: "state.local.gtm.last_submit.message" } },
          { kind: "append", target: "streams.activity", value: { from: "state.ui.submit_message" } },
          { kind: "emit", event: "app/init" },
          { kind: "persist", scope: "local" },
        ],
      },
      {
        id: "gtm-submit-limit",
        on: "gtm/submit-limit-exceeded",
        actions: [
          {
            kind: "set",
            target: "ui.error",
            value: "Usage cap reached for spend submissions in this window.",
          },
          {
            kind: "append",
            target: "streams.activity",
            value: { template: "{{event.at}} · spend submission limit reached" },
          },
        ],
      },
      {
        id: "gtm-refresh",
        on: "app/refresh",
        actions: [{ kind: "emit", event: "app/init" }],
      },
    ],
  },
  output: {
    renderer: "hybrid",
    liveUpdates: true,
    streamPath: "streams.activity",
  },
  state: {
    variables: [
      { scope: "global", key: "dashboard", initial: {} },
      { scope: "local", key: "filters.window_days", initial: 30 },
      { scope: "local", key: "forms.gtm_spend.source", initial: "google" },
      { scope: "local", key: "forms.gtm_spend.medium", initial: "ads" },
      { scope: "local", key: "forms.gtm_spend.campaign", initial: "" },
      { scope: "local", key: "forms.gtm_spend.ad_id", initial: "" },
      { scope: "local", key: "forms.gtm_spend.creative_id", initial: "" },
      { scope: "local", key: "forms.gtm_spend.cost_usd", initial: "" },
      { scope: "local", key: "forms.gtm_spend.clicks", initial: "" },
      { scope: "local", key: "forms.gtm_spend.impressions", initial: "" },
      { scope: "local", key: "forms.gtm_spend.dedupe_key", initial: "" },
      { scope: "ui", key: "loading", initial: true },
      { scope: "ui", key: "error", initial: null },
      { scope: "ui", key: "submit_message", initial: "" },
      { scope: "ui", key: "status_message", initial: "" },
      { scope: "streams", key: "activity", initial: [] },
    ],
    persistence: {
      key: "ops-gtm-dashboard-v3",
      local: true,
      server: false,
      autosaveMs: 500,
    },
    enableUndoRedo: true,
    enableReplay: true,
    resumeEvent: "app/init",
  },
  permissions: {
    defaultTier: "free",
    gates: [
      {
        id: "creative_depth",
        requires: "pro",
        message: "PRO unlocks deep creative-level analytics and ad diagnostics.",
      },
    ],
    usageLimits: [
      {
        id: "gtm_submit",
        event: "gtm/spend-submit",
        max: 12,
        window: "day",
      },
      {
        id: "gtm_refresh",
        event: "app/refresh",
        max: 40,
        window: "session",
      },
    ],
  },
  composition: {
    pipeline: ["ops-gtm-dashboard", "ops-growth-dashboard", "ops-revenue-dashboard"],
    sharedState: [{ from: "global.dashboard.headline.revenue_usd", to: "global.shared.revenue_usd" }],
  },
  sandbox: {
    allowedActions: [
      "analytics.fetchGtmDashboard",
      "analytics.upsertGtmSpend",
      "runtime.nowDate",
      "runtime.noop",
    ],
    maxActionMs: 6000,
    maxEventsPerMinute: 260,
  },
};
