"use client";

import { useMemo, useState } from "react";

import {
  ScenarioAppRuntime,
  getScenarioDefinition,
  scenarioPlatformActions,
  type ScenarioDefinition,
} from "@/features/scenario-engine";

type ParseResult = {
  definition: ScenarioDefinition | null;
  error: string | null;
};

const FALLBACK_TEMPLATE = {
  id: "custom-mini-app",
  type: "tool",
  version: 1,
  title: "Custom Mini App",
  description: "Generated from Scenario DSL JSON.",
  layout: {
    panels: [
      {
        id: "custom-hero",
        kind: "hero",
        renderer: "dom",
        kicker: "Generator",
        title: "Custom Mini App",
        subtitle: "Edit JSON and run inside the universal scenario runtime.",
      },
      {
        id: "custom-section",
        kind: "section",
        renderer: "dom",
        title: "Runtime output",
        subtitle: "This app is produced from JSON DSL only.",
        children: [
          {
            id: "custom-message",
            kind: "text",
            renderer: "dom",
            text: "{{state.ui.message}}",
          },
        ],
      },
    ],
  },
  inputs: {
    fields: [],
    interactions: [],
  },
  logic: {
    entryEvents: ["app/init"],
    steps: [
      {
        id: "custom-init",
        on: "app/init",
        actions: [
          { kind: "set", target: "ui.message", value: "Runtime boot completed." },
          { kind: "append", target: "streams.activity", value: { template: "{{event.at}} · app/init" } },
        ],
      },
    ],
  },
  output: {
    renderer: "dom",
    liveUpdates: true,
  },
  state: {
    variables: [
      { scope: "ui", key: "message", initial: "" },
      { scope: "streams", key: "activity", initial: [] },
    ],
    persistence: { key: "custom-mini-app", local: true, server: false, autosaveMs: 500 },
    enableUndoRedo: true,
    enableReplay: true,
    resumeEvent: "app/init",
  },
  permissions: {
    defaultTier: "free",
    gates: [],
    usageLimits: [],
  },
  sandbox: {
    allowedActions: ["runtime.noop"],
    maxActionMs: 3000,
    maxEventsPerMinute: 200,
  },
} satisfies ScenarioDefinition;

function parseScenarioDsl(jsonValue: string): ParseResult {
  try {
    const parsed = JSON.parse(jsonValue) as ScenarioDefinition;
    if (!parsed || typeof parsed !== "object") {
      return { definition: null, error: "DSL root must be an object." };
    }
    if (!parsed.id || !parsed.type || !parsed.layout || !parsed.logic || !parsed.state || !parsed.permissions) {
      return {
        definition: null,
        error: "DSL is missing required root keys (id/type/layout/logic/state/permissions).",
      };
    }
    if (!Array.isArray(parsed.layout.panels)) {
      return { definition: null, error: "layout.panels must be an array." };
    }
    if (!Array.isArray(parsed.logic.steps)) {
      return { definition: null, error: "logic.steps must be an array." };
    }
    if (!Array.isArray(parsed.inputs?.fields) || !Array.isArray(parsed.inputs?.interactions)) {
      return { definition: null, error: "inputs.fields and inputs.interactions must be arrays." };
    }
    return { definition: parsed, error: null };
  } catch (cause) {
    return {
      definition: null,
      error: cause instanceof Error ? cause.message : "Could not parse JSON.",
    };
  }
}

export function ScenarioGeneratorLab() {
  const growthReference = getScenarioDefinition("ops-growth-dashboard");
  const initialJson = useMemo(
    () => JSON.stringify(growthReference ?? FALLBACK_TEMPLATE, null, 2),
    [growthReference],
  );

  const [dslJson, setDslJson] = useState(initialJson);
  const [compiled, setCompiled] = useState<ScenarioDefinition | null>(growthReference ?? FALLBACK_TEMPLATE);
  const [error, setError] = useState<string | null>(null);

  function compileDsl() {
    const parsed = parseScenarioDsl(dslJson);
    setCompiled(parsed.definition);
    setError(parsed.error);
  }

  return (
    <section className="pv-panel p-5">
      <h2 className="text-lg font-semibold text-zinc-950">App Generator (DSL → Runtime)</h2>
      <p className="mt-2 text-sm text-zinc-600">
        Paste or edit Scenario DSL JSON. The app preview below is generated by the universal runtime.
      </p>

      <textarea
        value={dslJson}
        onChange={(event) => setDslJson(event.target.value)}
        className="pv-textarea mt-3 min-h-[240px] font-mono text-xs"
      />

      <div className="mt-3 flex flex-wrap gap-2">
        <button type="button" className="pv-button-primary !w-auto" onClick={compileDsl}>
          Compile DSL
        </button>
        <button
          type="button"
          className="pv-button-secondary !w-auto"
          onClick={() => {
            const next = JSON.stringify(FALLBACK_TEMPLATE, null, 2);
            setDslJson(next);
            const parsed = parseScenarioDsl(next);
            setCompiled(parsed.definition);
            setError(parsed.error);
          }}
        >
          Load template
        </button>
      </div>

      {error ? <p className="mt-2 text-sm text-rose-700">DSL error: {error}</p> : null}

      {compiled ? (
        <div className="mt-4 rounded-[1rem] border border-zinc-200 bg-zinc-50/60 p-3">
          <p className="mb-2 text-xs font-semibold uppercase tracking-[0.16em] text-zinc-500">Generated App Preview</p>
          <ScenarioAppRuntime definition={compiled} actions={scenarioPlatformActions} />
        </div>
      ) : null}
    </section>
  );
}
