#!/usr/bin/env bash
set -Eeuo pipefail

REPO_URL="${REPO_URL:-}"
BRANCH="${BRANCH:-main}"
TARGET_DIR="${TARGET_DIR:-/opt/website}"
SERVER_IP="${SERVER_IP:-}"
SITE_PORT="${SITE_PORT:-3000}"
ENABLE_FIREWALL="${ENABLE_FIREWALL:-true}"

usage() {
  cat <<'EOF'
Usage:
  bash scripts/deploy_ubuntu_ip.sh --repo-url <url> [--branch main] [--target-dir /opt/website] [--server-ip X.X.X.X] [--site-port 3000]

Environment variables:
  REPO_URL, BRANCH, TARGET_DIR, SERVER_IP, SITE_PORT, ENABLE_FIREWALL
  JWT_SECRET_KEY (optional, autogenerated if missing)
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo-url)
      REPO_URL="$2"
      shift 2
      ;;
    --branch)
      BRANCH="$2"
      shift 2
      ;;
    --target-dir)
      TARGET_DIR="$2"
      shift 2
      ;;
    --server-ip)
      SERVER_IP="$2"
      shift 2
      ;;
    --site-port)
      SITE_PORT="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

log() {
  printf '[deploy] %s\n' "$*"
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

if [[ -z "$REPO_URL" ]]; then
  echo "REPO_URL is required." >&2
  usage
  exit 1
fi

if [[ -z "$SERVER_IP" ]]; then
  SERVER_IP="$(curl -4fsSL https://api.ipify.org || true)"
fi
if [[ -z "$SERVER_IP" ]]; then
  SERVER_IP="$(hostname -I | awk '{print $1}')"
fi
if [[ -z "$SERVER_IP" ]]; then
  echo "Cannot detect SERVER_IP. Pass --server-ip explicitly." >&2
  exit 1
fi

JWT_SECRET_KEY="${JWT_SECRET_KEY:-}"
if [[ -z "$JWT_SECRET_KEY" ]]; then
  require_cmd openssl
  JWT_SECRET_KEY="$(openssl rand -hex 32)"
fi

require_cmd git
require_cmd curl
require_cmd awk
require_cmd sed
require_cmd grep
require_cmd sudo

if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker..."
  curl -fsSL https://get.docker.com | sudo sh
fi

sudo systemctl enable --now docker
if ! docker compose version >/dev/null 2>&1; then
  echo "Docker Compose plugin is required but unavailable." >&2
  exit 1
fi

TARGET_PARENT="$(dirname "$TARGET_DIR")"
sudo mkdir -p "$TARGET_PARENT"
sudo chown -R "$USER:$USER" "$TARGET_PARENT"

if [[ -d "$TARGET_DIR/.git" ]]; then
  log "Updating repository in $TARGET_DIR (branch: $BRANCH)"
  git -C "$TARGET_DIR" fetch --all --prune
  git -C "$TARGET_DIR" checkout "$BRANCH"
  git -C "$TARGET_DIR" pull --ff-only origin "$BRANCH"
else
  if [[ -e "$TARGET_DIR" && -n "$(ls -A "$TARGET_DIR" 2>/dev/null)" ]]; then
    echo "Target directory is not empty and not a git repository: $TARGET_DIR" >&2
    exit 1
  fi
  log "Cloning repository to $TARGET_DIR (branch: $BRANCH)"
  git clone --branch "$BRANCH" "$REPO_URL" "$TARGET_DIR"
fi

cd "$TARGET_DIR"

if [[ ! -f env.example ]]; then
  echo "env.example not found in $TARGET_DIR" >&2
  exit 1
fi
if [[ ! -f docker-compose.yml ]]; then
  echo "docker-compose.yml not found in $TARGET_DIR" >&2
  exit 1
fi

if [[ ! -f .env ]]; then
  cp env.example .env
fi

upsert_env() {
  local key="$1"
  local value="$2"
  local escaped
  escaped="$(printf '%s' "$value" | sed -e 's/[\/&]/\\&/g')"
  if grep -qE "^${key}=" .env; then
    sed -i -E "s|^${key}=.*|${key}=${escaped}|" .env
  else
    printf '%s=%s\n' "$key" "$value" >> .env
  fi
}

upsert_env "JWT_SECRET_KEY" "$JWT_SECRET_KEY"
upsert_env "CORS_ORIGINS" "http://${SERVER_IP}:${SITE_PORT},http://127.0.0.1:3000"
upsert_env "NEXT_PUBLIC_SITE_URL" "http://${SERVER_IP}:${SITE_PORT}"
upsert_env "BILLING_CHECKOUT_SUCCESS_URL" "http://${SERVER_IP}:${SITE_PORT}/dashboard?billing=success"
upsert_env "BILLING_CHECKOUT_CANCEL_URL" "http://${SERVER_IP}:${SITE_PORT}/plans?billing=cancel"
upsert_env "BILLING_PORTAL_RETURN_URL" "http://${SERVER_IP}:${SITE_PORT}/dashboard"
upsert_env "DOCKER_AUTH_COOKIE_ALLOW_INSECURE" "true"

log "Starting containers..."
docker compose pull --ignore-pull-failures
docker compose up -d --build
docker compose ps

log "Waiting for API health..."
for _ in {1..40}; do
  if curl -fsS http://127.0.0.1:8000/health >/dev/null 2>&1; then
    break
  fi
  sleep 2
done
curl -fsS http://127.0.0.1:8000/health >/dev/null

log "Waiting for WEB health..."
for _ in {1..40}; do
  if curl -fsS http://127.0.0.1:3000/health >/dev/null 2>&1; then
    break
  fi
  sleep 2
done
curl -fsS http://127.0.0.1:3000/health >/dev/null

if [[ "$ENABLE_FIREWALL" == "true" && -x "$(command -v ufw)" ]]; then
  log "Applying UFW rules..."
  sudo ufw allow OpenSSH
  sudo ufw allow "${SITE_PORT}/tcp"
  sudo ufw deny 8000/tcp || true
  sudo ufw deny 5432/tcp || true
  sudo ufw deny 6379/tcp || true
  sudo ufw --force enable
fi

log "Deploy complete."
echo "Site URL: http://${SERVER_IP}:${SITE_PORT}"
