from datetime import timedelta

DAILY_LADDER_REWARDS: tuple[int, ...] = (2, 2, 3, 3, 4, 4, 8)
STREAK_MILESTONE_REWARDS: dict[int, int] = {
    3: 2,
    7: 4,
    14: 8,
    30: 16,
}
STREAK_FREEZE_TOKEN_MILESTONES: dict[int, int] = {
    7: 1,
    14: 1,
    30: 2,
}

RANK_THRESHOLDS: tuple[int, ...] = (0, 40, 90, 150, 230, 320, 420, 540, 680, 840, 1020)
SPEND_STREAK_MULTIPLIERS: dict[int, float] = {
    1: 1.0,
    2: 1.1,
    3: 1.2,
    4: 1.3,
}

MISSION_DAILY_EARN_CAP = 50
MISSION_REWARD_EVENT_COOLDOWN_MINUTES = 5
ANTI_FARM_BREAKPOINTS: tuple[tuple[int, float], ...] = ((3, 1.0), (6, 0.7))
ANTI_FARM_FALLBACK_FACTOR = 0.4
STREAK_SURPRISE_PITY_THRESHOLD = 9
STREAK_SURPRISE_HIT_CHANCE_PERCENT = 10

SEGMENT_MISSION_LOOKBACK_HOURS = 72
SEGMENT_SPEND_LOOKBACK_DAYS = 7
HOARDER_BALANCE_THRESHOLD = 25
HOARDER_SPEND_RECENT_MAX = 1
SPENDER_SPEND_RECENT_MIN = 3

FIRST_PURCHASE_BONUS_LUMENS = 4
LOCKED_CASHBACK_RATE = 0.15
LOCKED_CASHBACK_REQUIRED_MISSIONS = 2
LOCKED_CASHBACK_UNLOCK_WINDOW_HOURS = 24
SECOND_PURCHASE_CHALLENGE_REWARD = 6
SECOND_PURCHASE_CHALLENGE_BOOST_PCT = 20
SECOND_PURCHASE_CHALLENGE_BOOST_MISSIONS = 2
SECOND_PURCHASE_CHALLENGE_WINDOW_HOURS = 48
CATCHUP_BOOST_PCT = 20
CATCHUP_BOOST_EXPIRY_HOURS = 48

DAILY_OFFER_ROTATION_SIZE = 3
NEAR_MISS_MAX_DELTA = 3
DEFAULT_PREMIUM_DAYS = 3
DEFAULT_BOOST_PCT = 20
DEFAULT_BOOST_MISSIONS = 3
PRICE_BAND_THRESHOLDS: tuple[tuple[int, str], ...] = (
    (8, "entry"),
    (15, "core"),
    (30, "mid"),
)

GOAL_WINDOW_DAYS = 7
INACTIVE_GOAL_INITIAL_TARGET = 2
INACTIVE_GOAL_NEXT_TARGET = 4
HOARDER_GOAL_INITIAL_TARGET = 2
HOARDER_GOAL_NEXT_TARGET = 3
SPENDER_GOAL_INITIAL_TARGET = 4
SPENDER_GOAL_NEXT_TARGET = 6

MISSION_REWARD_EVENT_COOLDOWN = timedelta(minutes=MISSION_REWARD_EVENT_COOLDOWN_MINUTES)
