import { mapPromptListToScenarios } from "@/features/scenarios/infrastructure/promptScenarioMapper";
import type { PromptListItem } from "@/lib/types";

import type { ScenarioDefinition } from "../../types";

type HomeWorkbenchLabels = {
  kicker: string;
  title: string;
  subtitle: string;
  queryLabel: string;
  queryPlaceholder: string;
  scenarioSelectLabel: string;
  taskLabel: string;
  taskPlaceholder: string;
  runNow: string;
  outputDetailed: string;
  outputConcise: string;
  refreshResult: string;
  openScenario: string;
  boostRuns: string;
  availableScenarios: string;
  liveResultTitle: string;
  liveResultSubtitle: string;
};

export type HomeWorkbenchScenarioInput = {
  prompts: PromptListItem[];
  labels: HomeWorkbenchLabels;
  language: "en" | "ru" | "tt";
};

export function buildHomeWorkbenchScenarioDefinition(input: HomeWorkbenchScenarioInput): ScenarioDefinition {
  const scenarios = mapPromptListToScenarios(input.prompts);
  const selectOptions = scenarios.map((scenario) => ({
    label: scenario.title,
    value: scenario.slug,
  }));
  const initialSlug = scenarios[0]?.slug ?? "";

  return {
    id: "home-workbench-runtime",
    type: "hybrid",
    version: 3,
    title: input.labels.title,
    description: input.labels.subtitle,
    layout: {
      panels: [
        {
          id: "home-workbench-hero",
          kind: "hero",
          renderer: "dom",
          kicker: input.labels.kicker,
          title: input.labels.title,
          subtitle: input.labels.subtitle,
        },
        {
          id: "home-workbench-controls",
          kind: "section",
          renderer: "dom",
          title: input.labels.title,
          subtitle: input.labels.subtitle,
          children: [
            {
              id: "home-workbench-form",
              kind: "form",
              renderer: "dom",
              formId: "home_workbench",
              fieldIds: ["home-query", "home-selected-scenario", "home-task-input"],
              submitLabel: input.labels.runNow,
              submitInteractionId: "home-submit-run",
            },
            {
              id: "home-workbench-mode-actions",
              kind: "actions",
              renderer: "dom",
              actions: [
                {
                  id: "home-mode-detailed",
                  label: input.labels.outputDetailed,
                  tone: "secondary",
                  interactionId: "home-set-detailed",
                },
                {
                  id: "home-mode-concise",
                  label: input.labels.outputConcise,
                  tone: "secondary",
                  interactionId: "home-set-concise",
                },
                {
                  id: "home-refresh",
                  label: input.labels.refreshResult,
                  tone: "secondary",
                  interactionId: "home-rebuild",
                },
                {
                  id: "home-open-scenario",
                  label: input.labels.openScenario,
                  tone: "secondary",
                  interactionId: "home-open-selected",
                },
                {
                  id: "home-boost",
                  label: input.labels.boostRuns,
                  tone: "secondary",
                  interactionId: "home-boost",
                },
              ],
            },
            {
              id: "home-guard-message",
              kind: "text",
              renderer: "dom",
              tone: "warning",
              text: "{{state.ui.guard_message}}",
              visibleWhen: { path: "state.ui.guard_message", exists: true },
            },
            {
              id: "home-remaining-runs",
              kind: "text",
              renderer: "dom",
              text: "Demo runs left: {{state.global.demo_status.remaining_runs}}",
              visibleWhen: { path: "state.global.demo_status.is_pro", equals: false },
            },
            {
              id: "home-unlimited-runs",
              kind: "text",
              renderer: "dom",
              tone: "success",
              text: "PRO: unlimited runs",
              visibleWhen: { path: "state.global.demo_status.is_pro", equals: true },
            },
          ],
        },
        {
          id: "home-workbench-selection",
          kind: "section",
          renderer: "dom",
          title: input.labels.availableScenarios,
          subtitle: "Filtered list is generated by the scenario engine.",
          children: [
            {
              id: "home-workbench-selection-table",
              kind: "table",
              renderer: "dom",
              source: "global.selection.visible",
              emptyText: "No scenarios found for current query.",
              columns: [
                { key: "title", label: "Title", format: "text" },
                { key: "category", label: "Category", format: "text" },
                { key: "qualityScore", label: "Quality", format: "number" },
                { key: "saveCount", label: "Saves", format: "number" },
              ],
            },
          ],
        },
        {
          id: "home-workbench-live",
          kind: "section",
          renderer: "hybrid",
          title: input.labels.liveResultTitle,
          subtitle: input.labels.liveResultSubtitle,
          children: [
            {
              id: "home-workbench-live-stream",
              kind: "stream",
              renderer: "stream",
              source: "streams.live_output",
              maxLines: 48,
              emptyText: "Run a scenario to generate live output.",
            },
            {
              id: "home-workbench-live-canvas",
              kind: "canvas",
              renderer: "canvas",
              source: "global.selection.visible",
              chart: "bars",
              height: 160,
            },
          ],
        },
      ],
    },
    inputs: {
      fields: [
        {
          id: "home-query",
          formId: "home_workbench",
          label: input.labels.queryLabel,
          type: "text",
          bind: "local.query",
          placeholder: input.labels.queryPlaceholder,
          interactionId: "home-update-query",
        },
        {
          id: "home-selected-scenario",
          formId: "home_workbench",
          label: input.labels.scenarioSelectLabel,
          type: "select",
          bind: "local.selected_slug",
          options: selectOptions,
          interactionId: "home-update-selected",
        },
        {
          id: "home-task-input",
          formId: "home_workbench",
          label: input.labels.taskLabel,
          type: "textarea",
          bind: "local.task_input",
          placeholder: input.labels.taskPlaceholder,
          interactionId: "home-update-task",
        },
      ],
      interactions: [
        {
          id: "home-update-query",
          type: "input",
          source: "home-query",
          emits: "home/query-updated",
          payload: {
            bind: { from: "interaction.bind" },
            value: { from: "interaction.value" },
          },
        },
        {
          id: "home-update-selected",
          type: "input",
          source: "home-selected-scenario",
          emits: "home/selection-changed",
          payload: {
            bind: { from: "interaction.bind" },
            value: { from: "interaction.value" },
          },
        },
        {
          id: "home-update-task",
          type: "input",
          source: "home-task-input",
          emits: "form/update",
          payload: {
            bind: { from: "interaction.bind" },
            value: { from: "interaction.value" },
          },
        },
        {
          id: "home-submit-run",
          type: "submit",
          source: "home_workbench",
          emits: "home/run",
        },
        {
          id: "home-set-detailed",
          type: "click",
          source: "home-mode-detailed",
          emits: "home/mode-detailed",
        },
        {
          id: "home-set-concise",
          type: "click",
          source: "home-mode-concise",
          emits: "home/mode-concise",
        },
        {
          id: "home-rebuild",
          type: "click",
          source: "home-refresh",
          emits: "home/rebuild",
        },
        {
          id: "home-open-selected",
          type: "click",
          source: "home-open-scenario",
          emits: "home/open-selected",
        },
        {
          id: "home-boost",
          type: "click",
          source: "home-boost",
          emits: "home/boost",
        },
      ],
    },
    logic: {
      entryEvents: ["app/init"],
      steps: [
        {
          id: "home-init",
          on: "app/init",
          actions: [
            { kind: "emit", event: "home/recompute-selection" },
            { kind: "emit", event: "home/rebuild" },
          ],
        },
        {
          id: "home-query-updated",
          on: "home/query-updated",
          actions: [
            { kind: "set_path", targetFrom: "bind", valueFrom: "value" },
            { kind: "emit", event: "home/recompute-selection" },
          ],
        },
        {
          id: "home-selection-changed",
          on: "home/selection-changed",
          actions: [
            { kind: "set_path", targetFrom: "bind", valueFrom: "value" },
            { kind: "emit", event: "home/recompute-selection" },
          ],
        },
        {
          id: "home-task-update",
          on: "form/update",
          actions: [{ kind: "set_path", targetFrom: "bind", valueFrom: "value" }],
        },
        {
          id: "home-recompute-selection",
          on: "home/recompute-selection",
          actions: [
            {
              kind: "invoke",
              actionId: "scenarios.computeSelection",
              input: {
                scenarios: { from: "state.global.scenarios" },
                query: { from: "state.local.query" },
                selected_slug: { from: "state.local.selected_slug" },
              },
              assign: "global.selection",
            },
            {
              kind: "set",
              target: "local.selected_slug",
              value: { from: "state.global.selection.selected.slug", fallback: "" },
            },
            {
              kind: "invoke",
              actionId: "scenarios.fetchDemoRunStatus",
              input: {
                prompt_slug: { from: "state.local.selected_slug" },
              },
              assign: "global.demo_status",
            },
            {
              kind: "append",
              target: "streams.activity",
              value: { template: "{{event.at}} · selected {{state.local.selected_slug}}" },
            },
          ],
        },
        {
          id: "home-mode-detailed",
          on: "home/mode-detailed",
          actions: [
            { kind: "set", target: "local.output_mode", value: "detailed" },
            { kind: "emit", event: "home/rebuild" },
          ],
        },
        {
          id: "home-mode-concise",
          on: "home/mode-concise",
          actions: [
            { kind: "set", target: "local.output_mode", value: "concise" },
            { kind: "emit", event: "home/rebuild" },
          ],
        },
        {
          id: "home-rebuild-output",
          on: "home/rebuild",
          actions: [
            {
              kind: "invoke",
              actionId: "scenarios.buildLiveResult",
              input: {
                language: { from: "state.global.language" },
                title: { from: "state.global.selection.selected.title", fallback: "Scenario" },
                summary: { from: "state.global.selection.selected.summary", fallback: "No summary" },
                category: { from: "state.global.selection.selected.category", fallback: "utility" },
                task_input: { from: "state.local.task_input" },
                output_depth: { from: "state.local.output_mode" },
                variation_seed: { from: "state.local.variation_seed" },
              },
              assign: "global.live_result",
            },
            {
              kind: "invoke",
              actionId: "runtime.splitLines",
              input: {
                value: { from: "state.global.live_result" },
              },
              assign: "streams.live_output",
            },
          ],
        },
        {
          id: "home-run",
          on: "home/run",
          actions: [
            {
              kind: "invoke",
              actionId: "scenarios.trackDemoRun",
              input: {
                prompt_slug: { from: "state.local.selected_slug" },
                task_input: { from: "state.local.task_input" },
              },
              assign: "local.last_run",
            },
            {
              kind: "set",
              target: "global.demo_status",
              value: { from: "state.local.last_run.status", fallback: {} },
            },
            {
              kind: "set",
              target: "ui.guard_message",
              value: { from: "state.local.last_run.message", fallback: null },
            },
            { kind: "append", target: "streams.activity", value: { template: "{{event.at}} · run executed" } },
            { kind: "emit", event: "home/rebuild" },
          ],
        },
        {
          id: "home-boost-runs",
          on: "home/boost",
          actions: [
            {
              kind: "invoke",
              actionId: "scenarios.purchaseDemoRunBoost",
              input: {
                prompt_slug: { from: "state.local.selected_slug" },
              },
              assign: "local.last_boost",
            },
            {
              kind: "set",
              target: "ui.guard_message",
              value: { from: "state.local.last_boost.message", fallback: null },
            },
            {
              kind: "invoke",
              actionId: "scenarios.fetchDemoRunStatus",
              input: {
                prompt_slug: { from: "state.local.selected_slug" },
              },
              assign: "global.demo_status",
            },
          ],
        },
        {
          id: "home-open-selected",
          on: "home/open-selected",
          actions: [
            {
              kind: "invoke",
              actionId: "runtime.navigate",
              input: {
                href: {
                  template: "/prompt/{{state.local.selected_slug}}",
                },
                target: "_self",
              },
            },
          ],
        },
      ],
    },
    output: {
      renderer: "hybrid",
      liveUpdates: true,
      streamPath: "streams.live_output",
    },
    state: {
      variables: [
        { scope: "global", key: "language", initial: input.language },
        { scope: "global", key: "scenarios", initial: scenarios },
        { scope: "global", key: "selection.filtered", initial: scenarios },
        { scope: "global", key: "selection.visible", initial: scenarios.slice(0, 6) },
        { scope: "global", key: "selection.selected", initial: scenarios[0] ?? null },
        { scope: "global", key: "demo_status", initial: {} },
        { scope: "global", key: "live_result", initial: "" },
        { scope: "local", key: "query", initial: "" },
        { scope: "local", key: "selected_slug", initial: initialSlug },
        { scope: "local", key: "task_input", initial: "" },
        { scope: "local", key: "output_mode", initial: "detailed" },
        { scope: "local", key: "variation_seed", initial: 0 },
        { scope: "ui", key: "guard_message", initial: null },
        { scope: "streams", key: "live_output", initial: [] },
        { scope: "streams", key: "activity", initial: [] },
      ],
      persistence: {
        key: "home-workbench-runtime-v3",
        local: true,
        server: false,
        autosaveMs: 500,
      },
      enableUndoRedo: true,
      enableReplay: true,
      resumeEvent: "app/init",
    },
    permissions: {
      defaultTier: "free",
      gates: [],
      usageLimits: [
        {
          id: "home_run",
          event: "home/run",
          max: 120,
          window: "session",
        },
      ],
    },
    composition: {
      pipeline: ["home-workbench-runtime", "ops-growth-dashboard", "ops-revenue-dashboard"],
      sharedState: [{ from: "local.selected_slug", to: "global.shared.last_selected_slug" }],
    },
    sandbox: {
      allowedActions: [
        "scenarios.computeSelection",
        "scenarios.fetchDemoRunStatus",
        "scenarios.trackDemoRun",
        "scenarios.purchaseDemoRunBoost",
        "scenarios.buildLiveResult",
        "runtime.splitLines",
        "runtime.navigate",
      ],
      maxActionMs: 6000,
      maxEventsPerMinute: 320,
    },
  };
}
